### ISSUE TITLE
move to Rust 2018 edition

### ISSUE THREAD

**Issue by DCjanus** [DCjanus/nabu#2]
When it's ready

**Comment by whtsky** [comment]
[![LGTM](https://lgtm.in/p/oqB4ZwVkq)](https://lgtm.in/i/oqB4ZwVkq)

**Comment by DCjanus** [comment]
The Rust core team has decided to postpone the release of Rust 2018 edition, it will be almost Rust 2019.

**Comment by DCjanus** [comment]
目前使用了2018 edition的feature，也就意味着stable版本无法构建通过，每次push都要收到一封CI构建失败的邮件，艰难。
