### ISSUE TITLE
构建Docker镜像时的网络问题

### ISSUE THREAD

**Issue by DCjanus** [DCjanus/nabu#4]
在Docker中使用Cargo构建项目时，其第一步是下载全量crates.io的索引信息，在国内构建时，由于网络环境影响，这一过程极为缓慢，故选择使用国内镜像，这有效提升了本地开发阶段的build体验。

但考虑到将来可能支持在Heroku等海外网络环境下进行构建，此时使用国内镜像可能适得其反，此时应该避免使用国内镜像。

目前想到的办法是，在Docker build时，脚本判断当前网络环境，自动选择是否使用国内镜像。

**Comment by whtsky** [comment]
#今天dc摸鱼了吗

隔壁项目有用 ARG 指定用不用国内镜像的操作，感觉比自动判断撸棒很多

**Comment by DCjanus** [comment]
说得好，我决定用ARG了

**Comment by DCjanus** [comment]
implemented
